### ISSUE TITLE
More CLI content?

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p3-intro-to-cli#2]
### Canvas Link

https://learning.flatironschool.com/courses/6049/pages/intro-to-clis?module_item_id=468042

### Concern

I know that there's already a lot to do, but are there plans to build out more CLI related labs / readings? As somebody who hasn't built a CLI before (similar to students) I feel like I would be at a loss as to where to start. It feels like CLIs could have their own more in-depth module, similar to what we currently do with Sinatra in phase 3.

**Comment by professor-ben** [comment]
Hey Matt,

This is definitely on our radar, but it's not something we can get to right this second. I am aiming to have at least one more lesson on CLIs (using Click) before go-live.

-Ben

**Comment by Matt-Eva** [comment]
Awesome, thanks for the follow-up, Ben!
