### ISSUE TITLE
Missing lib/

### ISSUE THREAD

**Issue by darkcohiba** [learn-co-curriculum/python-p3-intro-to-cli#4]
### Canvas Link

https://learning.flatironschool.com/courses/6049/pages/intro-to-clis?module_item_id=468042

### Concern

I tried to do a PR but am unsure of the process at this time. 

I could not get this to work without adding the lib/ before 'reports/grade_report.txt'

**Comment by professor-ben** [comment]
Thanks for raising an issue! I'm addressing this now and it should be ready to view on GitHub by EOD today.
